### ISSUE TITLE
Server crash on startup after update. Exception in server tick loop     at sonar.core.inventory.SonarLargeInventory.insertItem

### ISSUE THREAD

**Issue by ProsperCraft** [SonarSonic/Sonar-Core#10]
http://pastebin.com/G5EHH3Gq

After updating to the SonarCore-1.9.4-3.1.5 version in the Allthemods modpack 1.29 the existing world crashed on load.

Once I disabled the sonarcore and calculator mods, started the world which wiped their blocks from the chunk that was loading, then re-enabling the mods the server started fine.

**Comment by SonarSonic** [comment]
Fixed in dev
