### ISSUE TITLE
Server Crash BoP grass

### ISSUE THREAD

**Issue by ProsperCraft** [SonarSonic/Sonar-Core#11]
http://pastebin.com/G5TB2ANG

**Comment by ProsperCraft** [comment]
Another if it helps - 
http://pastebin.com/6Fqb2ixw

**Comment by ProsperCraft** [comment]
This one looks different perhaps it will help.
http://pastebin.com/ATSYWYnR

**Comment by SonarSonic** [comment]
Fixed in dev
