### ISSUE TITLE
Accessing Calculator Machines with Capabilities?

### ISSUE THREAD

**Issue by davqvist** [SonarSonic/Sonar-Core#13]
Forge: 12.18.2.2125
Calculator: 1.9.4-3.1.2
Sonar Core: 1.9.4-3.1.6
MC Version: 1.10.2

If I wrench a Calculator machine like the Analyzing Chamber to output, only EnderIO ItemConduits or Hoppers are able to pull out items, ExtraUtils Transfer Pipes or Actually Additions Item Laser Relay or the ESD don't work. I haven't tested it with other pipes. I'm no expert, but after a quick look at the code it seems you're not supporting the new Forge Capabilities and those mods only support those (forgive me if I'm wrong). Not sure if to report it here or in the Calculator github, but given that it should be probably fixed here, I'm reporting it here.

**Comment by SonarSonic** [comment]
Fixed in Dev

**Comment by davqvist** [comment]
Thanks a lot for the update. Unfortunately it doesn't work fully. I updated SonarCore and Calculator to the newest version and loaded my test world. It loaded indefinitely on world load and I had to kill the Minecraft process. I had a 500.000 line big fml-client-latest.log with errors starting from line 20.000. I can't upload all to pastebin, so here is the pastebin starting from shortly before the error: http://pastebin.com/8z17C7L8

Then I loaded a new world and tried working with the Analyzing Chamber. I've put a circuit in so that I have a output for green and red, wrenched one side to red and put transfer nodes one on red and one on green. This seemed to work, I only checked the transfer node on red at least and it worked. Then I attached Transfer Pipes to the nodes and linked them all to an inventory. I then put another circuit into the Analyzing Chamber and then it crashed: http://pastebin.com/93z2rzn7

So it seems kind of working, but crashes unfortunately. Not sure if the first problem is the same cause as the second. Not sure if I can give you more information about the first issue as I have a lot going on in the test world, mainly a automated Circuit processing line with EnderIO Conduits as other stuff didn't work and on the Analyzing Chamber I was trying out Actually Additions Item Laser Relays and Transfer Nodes as described in the initial bug report.

Again thanks a lot for your work.

**Comment by SonarSonic** [comment]
The first of these crashes is now fixed.. the second one I haven't been able to recreate yet

**Comment by davqvist** [comment]
So I made a new instance with no other mods than SonarCore, Calculator, JEI, ExtraUtilities and Actually Additions to make sure that no other mods influence it. I've put an Anlyzing Chamber 2 blocks above ground, wrenched the bottom to red, put Circuits in and out manually until I got one that had a side output for red. I then placed a Transfer Node from ExtraUtils on the bottom (red) and on the side (green). I looked in both Transfer Nodes and both had the item in them. I then placed a Transfer Pipe below the bottom Tranfer Node and it crashed with the same error message. Not sure if that is ExU2's problem or yours but given that ExU2's Transfer Nodes and Pipes work fine with everything else, I would appreciate if you take a second look. Thanks a lot for your work.

**Comment by barnumbirr** [comment]
Hello there,

Same as @davqvist but with EnderIO (v.3.0.1.145) Item Conduits and Sonarcore (v.3.1.9) and Calculator (v.3.1.4). http://pastebin.com/e7jY3ifF
Issue must be with Calculator or Sonarcore because I've been able to reproduce the crash with both EnderIO and ExUtils2.

Cheers.

**Comment by barnumbirr** [comment]
@SonarSonic do you have any news on this? We've been stuck with an unplayable server for a week now 😢

**Comment by SonarSonic** [comment]
@mrsmn Posting an update to SonarCore now, which should resolve this.

**Comment by barnumbirr** [comment]
@SonarSonic Awesome, thank you. I'll give it a spin as soon as Curse updates the version.

**Comment by barnumbirr** [comment]
@SonarSonic Unfortunately we now experience a different client/server crash: http://pastebin.com/RjJsKn1C
Nothing was changed client or server side except for the Sonarcore update from 3.1.9 to 3.2.0.

Hope this helps.

**Comment by SonarSonic** [comment]
@mrsmn I've posted a Calculator update, should be fixed now

**Comment by davqvist** [comment]
Worked in my test, thanks a lot.

**Comment by barnumbirr** [comment]
Same here, everything working fine again. Thanks @SonarSonic, awesome work.
