### ISSUE TITLE
1.10.2 - Server crash with latest sonar core

### ISSUE THREAD

**Issue by b0bst3r** [SonarSonic/Sonar-Core#15]
http://pastebin.ubuntu.com/23700934/

Similar to the pastebins in the new post here - https://github.com/SonarSonic/Sonar-Core/issues/13

SonarCore-1.10.2-3.1.7
Calculator-1.10.2-3.1.3

**Comment by SonarSonic** [comment]
Compiling issue...should be fixed when I next post an update

**Comment by P3pp3rF1y** [comment]
Currently our server suffers from this error and thus we can't start it. 
Any thoughts on when you may be releasing the fix?

**Comment by SonarSonic** [comment]
Should be fixed in next update..

**Comment by SonarSonic** [comment]
@b0bst3r @P3pp3rF1y Fixed in latest update same as #13

**Comment by P3pp3rF1y** [comment]
thanks
