### ISSUE TITLE
1.10.2 - Items UI broken

### ISSUE THREAD

**Issue by barnumbirr** [SonarSonic/Sonar-Core#16]
Hello,

after the upgrade to Sonarcore 3.2.0 / Calculator 3.1.5 (which still diplays v.3.1.4 in Forge "Mod options") a few Item UIs are completely broken. When entering a brand new single player world to test out Calculator Locators and Plugs, the Plug has the Locator UI and vice versa.

Sorry for the half assed bug report but this isn't easy to explain without a screencast and I'm not near my computer right now.

**Comment by SonarSonic** [comment]
This is literally impossible, what hahahahah. Can't recreate this at all...

**Comment by barnumbirr** [comment]
Tried it out again: can't reproduce it either. Well that was weird.
