### ISSUE TITLE
Stable Stone Using Incorrect Dyes

### ISSUE THREAD

**Issue by Darkosto** [SonarSonic/Sonar-Core#17]
Hello! 

I was checking out some of the mod's items and found that many of the stable stones are mismatched with the dye used to craft them. Cyan stones take yellow dye, etc. 

There's also a stone named "Light Stable Stone", I assume this is meant to be "Light gray" maybe?

mod version: 3.2.1
MC: 1.10.2
Forge: 2202

Thanks for checking this out!
Darkosto

**Comment by SonarSonic** [comment]
Sure, i'll take a look soon. Also you aren't by any chance the Sky Factory 3 dev are you. I might as well let you know the duping bugs have been fixed so you can re-enable flux buffers as people seemed to think that was why you'd disabled them... thanks :)

P.S sorry if I have the wrong person

**Comment by Darkosto** [comment]
Yes, I'm the dev for SF3.

I did remove them because they had a hand in a duplication bug and I spoke to the original dev who informed me that he was no longer modding. So, instead of removing the entirety of the mod, I removed the items necessary to complete the dupe bug. I didn't catch on the change logs that it had been fixed up, I'll check it out and add them back in to the pack.

Thanks!

edit: I just realized that you're Ollie :P Welcome back!

**Comment by SonarSonic** [comment]
I'm the dev o/. I'm back now. Probably not forever.

**Comment by SonarSonic** [comment]
opps

**Comment by SonarSonic** [comment]
Fixed in dev
