### ISSUE TITLE
crash involving sonar core and practical logistics fluid info interface

### ISSUE THREAD

**Issue by OmegaCenti** [SonarSonic/Sonar-Core#2]
client log https://gist.github.com/OmegaCenti/3cd5cf7799ed815ba8d8

crash log https://gist.github.com/OmegaCenti/686e93cace0c8aec3078

I was cycling through the fluid button at the top while it was attached to a node which was attached to a botania mana pool

**Comment by SonarSonic** [comment]
Thanks for reporting, fixed in dev
