### ISSUE TITLE
Reinforced Fence gets destroyed on left click and doesn't drop

### ISSUE THREAD

**Issue by davqvist** [SonarSonic/Sonar-Core#20]
SonarCore 3.2.1
Forge 12.18.3.2221
Minecraft 1.10.2

When I left click a Reinforced Stone Fence, it gets immediately destroyed and doesn't drop, just if I were in creative mode, the Reinforced Dirt Fence gets immediately destroyed as well, but does drop.

**Comment by SonarSonic** [comment]
Fixed in dev
