### ISSUE TITLE
Crash after updating to Sonar Core 3.2.3 (1.10.2)

### ISSUE THREAD

**Issue by ate0ate** [SonarSonic/Sonar-Core#21]
I had this crash upon world load so I downgraded to the previous sonar core and broke my calculator machines, then upgraded back to Sonar Core 3.2.3. The world loaded successfully this time but now I crash whenever I go to place a precision chamber or processing chamber, and probably other machines too. Reverting to the prior SonarCore seems to work.

http://pastebin.com/h8QVw7DZ

This is using forge 12.18.3.2221

EDIT: I get the same crash even starting a new world and giving myself a precision chamber creatively then attempting to place it. I can't load the world after placing the precision chamber without crashing unless I revert to Sonar Core 3.2.2.

**Comment by b0bst3r** [comment]
Confirmed same error happened here. 3.2.3 is not a good version.

**Comment by SonarSonic** [comment]
Fixed in dev. Update Calculator to 3.1.8
