### ISSUE TITLE
java.lang.AbstractMethodError in a UI thread with Calculator's Power Cube

### ISSUE THREAD

**Issue by enkryptor** [SonarSonic/Sonar-Core#22]
After updating to 3.2.3 I got a java.lang.AbstractMethodError exception:
java.lang.AbstractMethodError: sonar.core.inventory.AbstractSonarInventory.func_70296_d()V

http://pastebin.com/hXEVjvbE

3.2.2 works fine.

How to reproduce: Install the Calculator mod, craft a Power Cube, open its GUI, try to put anything in its slot.

**Comment by SonarSonic** [comment]
Fixed in dev. Update Calculator to 3.1.8
