### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by MinoCraft** [SonarSonic/Sonar-Core#24]
Hello! 
I'm playing on server with Flux Networks and other mods.
I'm using a basic flux storage in my  network and it work fine but sometimes the serveur crash =/ 
you can see the crash report [here](https://www.dropbox.com/s/ei6r7171zus0jzl/crash-2017-02-19_19.51.08-server.txt?dl=0) 

Thanks in advance !

**Comment by SonarSonic** [comment]
Thanks for reporting, was very useful in resolving some other even more serious issues. Thanks again.
Fixed in dev.
