### ISSUE TITLE
[1.10.2-3.2.2+] Fence's do not connect to each other

### ISSUE THREAD

**Issue by jwmwebdev** [SonarSonic/Sonar-Core#26]
Forge: 12.18.3.2239
Sonar Core: 1.10.2-3.2.2 to 1.10.2-3.2.5

Placed like fence's from sonar core next to each other. They do not connect, as if they were non-identical fence's from older minecraft versions.

Tested Reinforced stone brick, reinforced stone, reinforced dirt, and reinforced dirt brick fence's. Bug does not exist in the 3.2.1 version.

**Comment by Boolyman** [comment]
Came to report this same problem.   Hopefully this 9 day old ticket isnt an indication that this mod is abandoned.

**Comment by SonarSonic** [comment]
Fixed in dev
