### ISSUE TITLE
[1.10.2-3.2.5] Reinforced Stone Stairs Not solid 

### ISSUE THREAD

**Issue by KendirkRS** [SonarSonic/Sonar-Core#31]
As seen in image i think it only this upside down corner type but its not solid and can be used like an xray
sonarcore:ReinforcedStoneStairs

![image](https://cloud.githubusercontent.com/assets/17441461/24084253/8b22f290-0cde-11e7-87a8-122370414bd8.png)
and another
http://i.imgur.com/Gxz6bAv.png

**Comment by Tokoshoran** [comment]
Related: The upside-down stairs, when placed into an inside-corner of upside-down stairs, has the missing eighth on the wrong corner. This is why it's becoming see-through: Minecraft thinks it should be solid there, but the code rotated it wrong.

**Comment by SonarSonic** [comment]
Should be fixed now.
