### ISSUE TITLE
[Suggestion] Config to disable redundant recipes with Calculator

### ISSUE THREAD

**Issue by Lykrast** [SonarSonic/Sonar-Core#40]
Since Calculator allows crafting most decorative blocks (like Stable Stone) using calculators, being able to also craft them in a standard crafting table is redundant. As such having some config to make them only craftable with Calculator without having to use CraftTweaker or similar would be nice.

**Comment by SonarSonic** [comment]
Fixed in dev. These recipes are intended to be only available when Calculator is not installed, so that is now the case again.
