### ISSUE TITLE
[1.12.1] Crash (most likely with applied energistics) 

### ISSUE THREAD

**Issue by erwin1234777** [SonarSonic/Sonar-Core#41]
Well, gonna paste the link for the crash here https://pastebin.com/3W3dNEDZ

**Comment by Sk11ppy** [comment]
I'm having the same issue as @erwin1234777 .  any idea what could be causing this?

**Comment by erwin1234777** [comment]
It says error with appeng (applied energistics). Appeng just updated and i also reported this to their author. however, i got this message as a reply: AE2 is an alpha, there where API changes. There is nothing we can do on our side.

Im trying to downgrade AE, havent booted it, ill let you know as soon as im able to play again @Lasrer

**Comment by digi-tal-it** [comment]
I can confirm this crash after updating from AE2 rv5-alpha 4 to alpha 6. 
Reverting to alpha 4 lets minecraft boot again. Here ist my crashlog:

https://pastebin.com/De9SU41M

(I am on mc 1.12.2)

**Comment by Peca21** [comment]
Can confirm on 1.12.1

**Comment by dancc7t** [comment]
im having the same problem, but the author says to post it here
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3130
latest AE2 Version (alpha-6) does not fix it.

**Comment by SonarSonic** [comment]
Hi All, This is just AE2 updating their API and us not updating yet. Luckily @pupnewfster has already fixed it and I should get the fix out soon.

**Comment by digi-tal-it** [comment]
Any date, when the fix will be available ?

Thanks for your work!!

**Comment by SonarSonic** [comment]
Fix is out.
