### ISSUE TITLE
[1.12.2-5.0.2] NoClassDefFoundError in SonarCore

### ISSUE THREAD

**Issue by DJJBanx** [SonarSonic/Sonar-Core#47]
https://pastebin.com/zV0M5wvA

Seems to be an error with an API (AppEng?)

**Comment by robaimes** [comment]
@DJJBanx You'll have to backdate Sonar Core to 5.0.1 and wait for Applied Llamagistics to update, or use official AE2 for now. Thiakil is aware of the issue as mentioned [here](https://github.com/thiakil/Applied-Energistics-2/issues/81#issuecomment-334585253) by p455w0rd.

Either way, this is is not an issue with Sonar Core.

**Comment by DJJBanx** [comment]
Thanks
