### ISSUE TITLE
Incompatibility with Applied Llamagistics

### ISSUE THREAD

**Issue by Kevun1** [SonarSonic/Sonar-Core#49]
Sonar Crashes with Applied Llaamagistics on startup: https://pastebin.com/vJQjpHRP

Sonar Core v5.0.2
Minecraft 1.12
Forge 2515

The reason is because AE2 updated their API to use IActionSource instead of BaseActionSource some time ago, but Llamagistics has not. Because the two mods have the same mod ID, Sonar Core doesn't differentiate between the two mods in the ASMLoader class and doesn't check if the interface exists. 

I opened an issue on Llamastics [here](https://github.com/thiakil/Applied-Energistics-2/issues/92), but the author claimed it needs to be handled on your end. Not sure if he's planning on updating the API to match AE2's or not.

It looks like to fix it you'll need to explicitly handle the case for AL, which I understand is pretty annoying. I know I could just use AE2, but AL has a bunch of nice features over it, and it would be a shame to have a fundamental incompatibility between some major mods. 

If you are willing to fix it from your end, I would greatly appreciate it. Thanks a lot for the work on your mods!

**Comment by Kevun1** [comment]
Actually, looks like you already closed an issue on this. Nevermind then.

**Comment by MokahTGS** [comment]
https://github.com/thiakil/Applied-Energistics-2/issues/92

So will this not be fixed?

**Comment by bonnedav** [comment]
Will someone please fix this?
