### ISSUE TITLE
Game crashed when using 1.12.x-5.0.5

### ISSUE THREAD

**Issue by Thenosis** [SonarSonic/Sonar-Core#54]
Problem:
My game crashed before it ever finished loading.

Expected:
Game to least make it to the menu screen.

How to replicate: 
Not sure. I'm building my own personal mod pack and I am using the current version of all included mods. 

Pastebin link:
https://pastebin.com/qDs5WHcq

As said above, I'm creating my own mod pack and have been modifying mods and removing and adding ones as I've determined their usefulness for myself. Right after the crash I lowered the version back to 5.0.4, this created an error in Flux Networks, which was to be expected, so I also went back to 3.0.2 for FN. This just happened this morning. After reversing the update everything loads with no problem.

**Comment by pupnewfster** [comment]
You need to also update calculator in addition to sonar-core, and flux networks.
`| UCH   | calculator               | 5.0.2                    | calculator-1.12.2-5.0.2.jar                     | None                                     |`
The latest version of calculator is 5.0.3

**Comment by Thenosis** [comment]
Okay, thank you so much for the help. Apparently, since Twitch is so stupid with their launcher I didn't even know Calculator had an update until I checked the versions page. Twitch really needs to fix their launcher, Hopefully they do soon.
