### ISSUE TITLE
Sonarcore chrashing after installing applied energistics

### ISSUE THREAD

**Issue by LejonLG** [SonarSonic/Sonar-Core#57]
Minecraft version 1.12.2

---- Minecraft Crash Report ----

WARNING: coremods are present:
  RBLoadingPlugin (RealBench-Mod-1.12.2.jar)
  CXLibraryCore (CXLibrary-1.12.1.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.6.3.jar)
  ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  LoadingPlugin (Random-Things-Mod-1.12.1.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 2/14/18 6:35 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SonarCore (sonarcore)
Caused by: java.lang.NoClassDefFoundError: appeng/api/networking/security/BaseActionSource
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at sonar.core.helpers.ASMLoader.getInstances(ASMLoader.java:89)
	at sonar.core.helpers.ASMLoader.getInventoryHandlers(ASMLoader.java:44)
	at sonar.core.helpers.ASMLoader.load(ASMLoader.java:37)
	at sonar.core.SonarCore.preInit(SonarCore.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: appeng.api.networking.security.BaseActionSource
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2967500016 bytes (2830 MB) / 4030201856 bytes (3843 MB) up to 4030201856 bytes (3843 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4048M -Xms4048M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2613 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version                  | Source                                          | Signature                                |
	|:----- |:----------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft               | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                     | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                     | 8.0.99.99                | forge-1.12.2-14.23.2.2613.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                   | 14.23.2.2613             | forge-1.12.2-14.23.2.2613.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | openmodscore            | 0.11.3                   | minecraft.jar                                   | None                                     |
	| UCH   | opencomputers|core      | 1.7.1.43                 | minecraft.jar                                   | None                                     |
	| UCH   | mercurius_updater       | 1.0                      | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| UCH   | actuallyadditions       | 1.12.1-r120              | Actually-Additions-Mod-1.12.1.jar               | None                                     |
	| UCH   | appliedenergistics2     | rv5-stable-8             | appliedenergistics2-rv5-stable-8.jar            | None                                     |
	| UCH   | baubles                 | 1.5.2                    | Baubles-Mod-1.12.2.jar                          | None                                     |
	| UCH   | biomesoplenty           | 7.0.1.2313               | BiomesOPlenty-1.12.2-7.0.1.2313-universal.jar   | None                                     |
	| UCH   | buildcraftlib           | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftcore          | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftbuilders      | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftenergy        | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftfactory       | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftrobotics      | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcraftsilicon       | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | buildcrafttransport     | 7.99.14                  | BuildCraft-Mod-1.12.2.jar                       | None                                     |
	| UCH   | codechickenlib          | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux            | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | cofhcore                | 4.3.10                   | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
	| UCH   | cofhworld               | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCH   | computercraft           | 1.80pr1                  | ComputerCraft-Mod-1.12.1.jar                    | None                                     |
	| UCH   | cucumber                | 1.0.3                    | Cucumber-Mod-1.12.2.jar                         | None                                     |
	| UCH   | cxlibrary               | 1.6.1                    | CXLibrary-1.12.1.jar                            | None                                     |
	| UCH   | enderstorage            | 2.4.0.122                | Ender-Storage-Mod-1.12.jar                      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | exnihilocreatio         | 1.12-0.1.5               | Ex-Nihilo-Creatio-Mod-1.12.1.jar                | None                                     |
	| UCH   | jei                     | 4.8.5.151                | jei_1.12.2-4.8.5.151.jar                        | None                                     |
	| UCH   | mantle                  | 1.12-1.3.1.21            | Mantle-Mod-1.12.1.jar                           | None                                     |
	| UCH   | tconstruct              | 1.12.2-2.9.0.55          | Tinkers-Construct-Mod-1.12.2.jar                | None                                     |
	| UCH   | extrautils2             | 1.0                      | extrautils2-1.12-1.7.3.jar                      | None                                     |
	| UCH   | zerocore                | 1.12-0.1.1.0             | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCH   | bigreactors             | 1.12.2-0.4.5.46          | ExtremeReactors-1.12.2-0.4.5.46.jar             | None                                     |
	| UCE   | sonarcore               | 5.0.1                    | sonarcore-1.12.2-5.0.1.jar                      | None                                     |
	| UCE   | fluxnetworks            | 3.0.1                    | Flux-Networks-Mod-1.12.1.jar                    | None                                     |
	| UCH   | ichunutil               | 7.1.4                    | iChun-Util-Mod-1.12.2.jar                       | None                                     |
	| UCH   | nei                     | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | ftbl                    | 4.2.5                    | FTBLib-1.12.1.jar                               | None                                     |
	| UCH   | giacomosfoundry         | 1.3.13                   | Giacomos-Foundry-Mod-1.12.2.jar                 | None                                     |
	| UCH   | guideapi                | 1.12-2.1.4-57            | Guide-API-1.12-2.1.4-57.jar                     | None                                     |
	| UCH   | hammercore              | 1.9.6.3                  | HammerCore-1.12.2-1.9.6.3.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCH   | waila                   | 1.8.23                   | Hwyla-1.8.23-B38_1.12.jar                       | None                                     |
	| UCH   | forgelin                | 1.5.1                    | Shadowfacts-Forgelin-1.12.2.jar                 | None                                     |
	| UCH   | teslacorelib            | 1.0.10                   | Tesla-Core-Lib-1.12.2.jar                       | None                                     |
	| UCH   | industrialforegoing     | 1.12.2-1.12.1            | Industrial-Foregoing-Mod-1.12.2.jar             | None                                     |
	| UCH   | inventorytweaks         | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2.jar                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironchest               | 1.12.2-7.0.34.820        | Iron-Chests-Mod-1.12.2.jar                      | None                                     |
	| UCH   | morefurnaces            | 1.10.1                   | More-Furnaces-Mod-1.12.1.jar                    | None                                     |
	| UCH   | mysticalagriculture     | 1.6.4                    | Mystical-Agriculture-Mod-1.12.1.jar             | None                                     |
	| UCH   | openmods                | 0.11.3                   | OpenModsLib-1.12.2.jar                          | None                                     |
	| UCH   | openblocks              | 1.7.3                    | OpenBlocks-Mod-1.12.2.jar                       | None                                     |
	| UCH   | opencomputers           | 1.7.1.43                 | OpenComputers-MC1.12.1-1.7.1.43.jar             | None                                     |
	| UCH   | randomthings            | 4.0.5                    | Random-Things-Mod-1.12.1.jar                    | None                                     |
	| UCH   | thermalfoundation       | 2.3.10                   | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UCH   | thermalexpansion        | 5.3.10                   | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |
	| UCH   | redstonearsenal         | 2.3.6                    | Redstone-Arsenal-Mod-1.12.1.jar                 | None                                     |
	| UCH   | rftools                 | 6.12                     | RFTools-Mod-1.12.jar                            | None                                     |
	| UCH   | simplyjetpacks          | 2.2.1.20                 | Simply-Jetpacks-2-Mod-1.11.2.jar                | None                                     |
	| UCH   | thermaldynamics         | 2.3.10                   | ThermalDynamics-1.12.2-2.3.10.4-universal.jar   | None                                     |
	| UCH   | twilightforest          | 3.0.0                    | Twilight-Forest-Mod-1.12.2.jar                  | None                                     |
	| UCH   | uncraftingtable         | 1.8-beta6                | Uncrafting-Table-Mod-1.12.1.jar                 | None                                     |
	| UCH   | xaerominimap            | 1.14.8                   | Xaeros_Minimap_1.14.8_Forge_1.12.jar            | None                                     |
	| UCH   | xnet                    | 1.4.0                    | XNet-Mod-1.12.1.jar                             | None                                     |
	| UCH   | teslacorelib_registries | 1.0.10                   | Tesla-Core-Lib-1.12.2.jar                       | None                                     |

	Loaded coremods (and transformers): 
RBLoadingPlugin (RealBench-Mod-1.12.2.jar)
  pw.prok.realbench.asm.RBTransformer
CXLibraryCore (CXLibrary-1.12.1.jar)
  cubex2.cxlibrary.CoreModTransformer
HammerCoreCore (HammerCore-1.12.2-1.9.6.3.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  
Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  invtweaks.forge.asm.ContainerTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2.jar)
  openmods.core.OpenModsClassTransformer
TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (Random-Things-Mod-1.12.1.jar)
  lumien.randomthings.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.77' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

**Comment by SonarSonic** [comment]
Update Sonar Core and Applied Energistics.
