### ISSUE TITLE
Trying to build and it can't find ElecCore

### ISSUE THREAD

**Issue by zackeezy** [SonarSonic/Sonar-Core#58]
> Warning:<i><b>root project 'Sonar-Core': Unable to resolve additional project configuration.</b>
Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':compileOnly'.
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find eleccore-rendering-library:ElecCore:1.12.2.
Required by:
    project :</i>

I downloaded ElecCore and built it, but when I put the built Jar in Sonar-Core/lib it still doesn't recognize it.  I saw that ElecCore has the /lib and a jar in there.  I was trying to maybe fix the issue with Calculator but this is really tripping me up.  I was maybe hoping I could get some help setting things up.

**Comment by SonarSonic** [comment]
How did you setup your development environment? 

If you download everything on the SonarCore GitHub and put it in a forge src folder and then run,

`gradlew setupDecompWorkspace -refresh-dependencies`

`gradlew eclipse` or `gradlew idea`

All the required mods should be downloaded automatically, if it still requires ones for the build.  Put those in your mod folder.

**Comment by zackeezy** [comment]
Okay thanks.
