### ISSUE TITLE
Crash on server join

### ISSUE THREAD

**Issue by C0rn3j** [SonarSonic/Sonar-Core#6]
Server forge 2046, client 2046/2049.

Modlist: http://pastebin.com/TR9vc0H4

Crashlog: http://pastebin.com/s5q0HjXe

This mod batch update caused this, in case it's not sonar core error: http://pastebin.com/kyCcvvVP

**Comment by C0rn3j** [comment]
Confirmed to be a sonar core/Calculator issue, downgraded them both to a previous version and game joins fine.

**Comment by SonarSonic** [comment]
Yeah i'm aware of this issue, should have a fix out in the next 20 mins

**Comment by SonarSonic** [comment]
Fix is finished
