### ISSUE TITLE
Bad performance on simulated inserts

### ISSUE THREAD

**Issue by fraenkelc** [SonarSonic/Sonar-Core#61]
Mod versions:
* calculator-1.12.2-5.0.2 
* sonarcore-1.12.2-5.0.4

I've tested a large setup of Atomic Multipliers (300). I'm feeding Circuits using TE Impulse Itemducts with resonant servos into these multipliers. When there's space in the machines everything is fine. When the machines fill up server TPS drops sharply.

![image](https://user-images.githubusercontent.com/4005102/38039834-6b10631a-32ae-11e8-8ed0-151ba205a4b6.png)

for the full flamegraph see https://gist.github.com/fraenkelc/1e3cdd01a713715debe984004f151f29

The issue seems to occur because the incoming item stack is cloned every time even on simulation runs.

**Comment by SonarSonic** [comment]
You should see a major performance improvement in the next version.
See: ebaee60b5e551841f64f6957c24903a21189fbd1
