### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by DAgility** [SonarSonic/Sonar-Core#63]
https://hastebin.com/iyoyigiqor.sql

Yup.

**Comment by SonarSonic** [comment]
You are using a beta applied-llamagistics, there is no need to use this as applied-energistics has stable builds available now.

**Comment by DAgility** [comment]
https://imgur.com/a/UcDvA38

**Comment by SonarSonic** [comment]
The difficulty is these mods identify as the same mod, applied-llamagistics still has the modid "appliedenergistics2" not "appliedllamagistics". So unless someone has a smart way of differentiating them, it'll be difficult to support both simultaneously.

**Comment by SonarSonic** [comment]
Really AL needs to update their API to the one used in the latest official AE2 release. So this is really a AL issue, as AE2 is more widely used and people who integrate with it will always use the latest API, rather than  the outdated version in AL.
