### ISSUE TITLE
New Calculator and New Flux Networks need version SC 5.0.13

### ISSUE THREAD

**Issue by Knito58** [SonarSonic/Sonar-Core#66]
... but only 5.0.12 is published on CurseForge.

**Comment by SonarSonic** [comment]
It's uploaded, waiting for CurseForge's approval.

You can also get it [here](https://maven.ironhide.de/sonar/sonarcore/1.12.2-5.0.13-10/sonarcore-1.12.2-5.0.13-10.jar)

**Comment by Knito58** [comment]
Thank you. This was not obvious. Didn't know that CurseForge approves uploads. That is another good point for downloading the mods from this location only.
