### ISSUE TITLE
NPE in TileHandlerForge

### ISSUE THREAD

**Issue by ruifung** [SonarSonic/Sonar-Core#67]
Results in this, on client.
 https://paste.dimdev.org/roxesikake.mccrash

I'm under the impression, that capabilities should be checked for null before using them.
It could also be that the calculator mod shouldn't be trying to inject energy on client side but. yeah.

The case in question is when placing a enderIO energy conduit onto a conductor mast.
And this is on a multiplayer server.  The server didn't crash, just the client.

Sonar Core 5.0.13-11
Calculator 5.0.8-4

**Comment by SonarSonic** [comment]
Fixed in dev
